#pragma once

namespace xhey::camera {

enum ErrorDomain : int {
    kErrorDomainDefault = 0,
    kErrorDomainCommonMedia = 0x1000,
    kErrorDomainDemux,
    kErrorDomainBitstreamConvert,
    kErrorDomainDecode,
    kErrorDomainGopStructureCache,
    kErrorDomainExportPipeline,
    kErrorDomainMattingBorder,

    kErrorDomainNetwork,
    kErrorDomainTime,

    kErrorDomainCommonRender = 0x2000,
};

enum ErrorType : int {
    kErrorTypeMediaKit = 50000,
    kErrorTypeOS,
    kErrorTypeApple,
    kErrorTypeFFmpeg,
    kErrorTypeWebP,
    kErrorTypeMediaCodec,
    kErrorTypeVideoToolBox,
    kErrorTypeGLES,
    kErrorTypeTurboJPEG,
    kErrorTypeStuck,
    kErrorTypeSignal,
};

enum ErrorCode : int {
    kErrorCodeOK = 0,
    kErrorCodeInvalidFile,
    kErrorCodeInvalidState,
    kErrorCodeInvalidData,
    kErrorCodeNotSupported,
    kErrorCodeIgnored,
    kErrorCodeTryAgain,
    kErrorCodeOutOfMemory,
    kErrorCodeDemuxerReconfig,
    kErrorCodeReTranscodeBecauseOfGreenFrames,
    kErrorCodeTryAgainExceedMaxCount,
    kErrorCodeCaptureImagePreviewFrameIsNullptr,
    kErrorCodeCaptureImageStillImageIsNullptr,
    kErrorCodeImageOpenFailed,
    kErrorCodeImageFileNotOpened,
    kErrorCodeImageWriteMetadataFailed,
    kErrorCodeImageReadFailed,
    kErrorCodeInvalidImageFormat,
    kErrorCodeImageCompressFailed,
    kErrorCodeVideoAlreadyOpened,
    kErrorCodeVideoNotOpened,
    kErrorCodeVideoWriteMetadataFailed,
    kErrorCodeInvalidNapiParam,
    kErrorCodeOpenVideoFailed,
    kErrorCodeInputFrameIsNullptr,
    kErrorCodeCreateAVSourceFailed,
    kErrorCodeCreateAVDemuxerFailed,
    kErrorCodeGetSourceFormatFailed,
    kErrorCodeGetTrackFormatFailed,
    kErrorCodeUnknownCodecType,
    kErrorCodeReadVideoFrameFailed,
    kErrorCodeReadAudioFrameFailed,
    kErrorCodeCreateAVDecoderFailed,
    kErrorCodeConfigureAVDecoderFailed,
    kErrorCodePrepareAVDecoderFailed,
    kErrorCodeStartAVDecoderFailed,
    kErrorCodePushInputBufferFailed,
    kErrorCodeSetSurfaceAVDecoderFailed,
    kErrorCodeSeekFailed,
    kErrorCodeEncoderConfigFailed,
    kErrorCodeEncoderStartFailed,
    kErrorCodeEncoderPreparFailed,
    kErrorCodeEncoderInitFailed,
    kErrorCodeEncoderResetFailed,
    kErrorCodeEncoderStopFailed,
    kErrorCompressImageToJpegFailed,
    kErrorCodeCreateAssetWriterFailed,
    kErrorCodeAssetWriterStartWritingFailed,
    kErrorCodeAssetWriterStopFailed,
    kErrorCodeAlreadyRecording,
    kErrorCodeNotRecording,
    kErrorCodeCreateDirectoryFailed,
    kErrorCodeNetworkNotInitialized,
    kErrorCodeJsonParseFailed,
    kErrorCodeServerTimeNotValid,
};

} // namespace xhey::camera
